tts_order_voice = {
  'English (United States)-Jenny-Female': 'en-US-JennyNeural',
 'English (United States)-Guy-Male': 'en-US-GuyNeural',
 'English (United States)-Ana-Female': 'en-US-AnaNeural',
 'English (United States)-Aria-Female': 'en-US-AriaNeural',
 'English (United States)-Christopher-Male': 'en-US-ChristopherNeural',
 'English (United States)-Eric-Male': 'en-US-EricNeural',
 'English (United States)-Michelle-Female': 'en-US-MichelleNeural',
 'English (United States)-Roger-Male': 'en-US-RogerNeural',
  'English (Australia)-Natasha-Female': 'en-AU-NatashaNeural',
 'English (Australia)-William-Male': 'en-AU-WilliamNeural',
 'English (Canada)-Clara-Female': 'en-CA-ClaraNeural',
 'English (Canada)-Liam-Male': 'en-CA-LiamNeural',
 'English (United Kingdom)-Libby-Female': 'en-GB-LibbyNeural',
 'English (United Kingdom)-Maisie-Female': 'en-GB-MaisieNeural',
 'English (United Kingdom)-Ryan-Male': 'en-GB-RyanNeural',
 'English (United Kingdom)-Sonia-Female': 'en-GB-SoniaNeural',
 'English (United Kingdom)-Thomas-Male': 'en-GB-ThomasNeural',
 'English (Hongkong)-Sam-Male': 'en-HK-SamNeural',
 'English (Hongkong)-Yan-Female': 'en-HK-YanNeural',
 'English (Ireland)-Connor-Male': 'en-IE-ConnorNeural',
 'English (Ireland)-Emily-Female': 'en-IE-EmilyNeural',
 'English (India)-Neerja-Female': 'en-IN-NeerjaNeural',
 'English (India)-Prabhat-Male': 'en-IN-PrabhatNeural',
 'English (Kenya)-Asilia-Female': 'en-KE-AsiliaNeural',
 'English (Kenya)-Chilemba-Male': 'en-KE-ChilembaNeural',
 'English (Nigeria)-Abeo-Male': 'en-NG-AbeoNeural',
 'English (Nigeria)-Ezinne-Female': 'en-NG-EzinneNeural',
 'English (New Zealand)-Mitchell-Male': 'en-NZ-MitchellNeural',
 'English (Philippines)-James-Male': 'en-PH-JamesNeural',
 'English (Philippines)-Rosa-Female': 'en-PH-RosaNeural',
 'English (Singapore)-Luna-Female': 'en-SG-LunaNeural',
 'English (Singapore)-Wayne-Male': 'en-SG-WayneNeural',
 'English (Tanzania)-Elimu-Male': 'en-TZ-ElimuNeural',
 'English (Tanzania)-Imani-Female': 'en-TZ-ImaniNeural',
 'English (South Africa)-Leah-Female': 'en-ZA-LeahNeural',
 'English (South Africa)-Luke-Male': 'en-ZA-LukeNeural',
 'Spanish (Argentina)-Elena-Female': 'es-AR-ElenaNeural',
 'Spanish (Argentina)-Tomas-Male': 'es-AR-TomasNeural',
 'Spanish (Bolivia)-Marcelo-Male': 'es-BO-MarceloNeural',
 'Spanish (Bolivia)-Sofia-Female': 'es-BO-SofiaNeural',
 'Spanish (Colombia)-Gonzalo-Male': 'es-CO-GonzaloNeural',
 'Spanish (Colombia)-Salome-Female': 'es-CO-SalomeNeural',
 'Spanish (Costa Rica)-Juan-Male': 'es-CR-JuanNeural',
 'Spanish (Costa Rica)-Maria-Female': 'es-CR-MariaNeural',
 'Spanish (Cuba)-Belkys-Female': 'es-CU-BelkysNeural',
 'Spanish (Dominican Republic)-Emilio-Male': 'es-DO-EmilioNeural',
 'Spanish (Dominican Republic)-Ramona-Female': 'es-DO-RamonaNeural',
 'Spanish (Ecuador)-Andrea-Female': 'es-EC-AndreaNeural',
 'Spanish (Ecuador)-Luis-Male': 'es-EC-LuisNeural',
 'Spanish (Spain)-Alvaro-Male': 'es-ES-AlvaroNeural',
 'Spanish (Spain)-Elvira-Female': 'es-ES-ElviraNeural',
 'Spanish (Equatorial Guinea)-Teresa-Female': 'es-GQ-TeresaNeural',
 'Spanish (Guatemala)-Andres-Male': 'es-GT-AndresNeural',
 'Spanish (Guatemala)-Marta-Female': 'es-GT-MartaNeural',
 'Spanish (Honduras)-Carlos-Male': 'es-HN-CarlosNeural',
 'Spanish (Honduras)-Karla-Female': 'es-HN-KarlaNeural',
 'Spanish (Mexico)-Dalia-Female': 'es-MX-DaliaNeural',
 'Spanish (Mexico)-Jorge-Male': 'es-MX-JorgeNeural',
 'Spanish (Nicaragua)-Federico-Male': 'es-NI-FedericoNeural',
 'Spanish (Nicaragua)-Yolanda-Female': 'es-NI-YolandaNeural',
 'Spanish (Panama)-Margarita-Female': 'es-PA-MargaritaNeural',
 'Spanish (Panama)-Roberto-Male': 'es-PA-RobertoNeural',
 'Spanish (Peru)-Alex-Male': 'es-PE-AlexNeural',
 'Spanish (Peru)-Camila-Female': 'es-PE-CamilaNeural',
 'Spanish (Puerto Rico)-Karina-Female': 'es-PR-KarinaNeural',
 'Spanish (Puerto Rico)-Victor-Male': 'es-PR-VictorNeural',
 'Spanish (Paraguay)-Mario-Male': 'es-PY-MarioNeural',
 'Spanish (Paraguay)-Tania-Female': 'es-PY-TaniaNeural',
 'Spanish (El Salvador)-Lorena-Female': 'es-SV-LorenaNeural',
 'Spanish (El Salvador)-Rodrigo-Male': 'es-SV-RodrigoNeural',
 'Spanish (United States)-Alonso-Male': 'es-US-AlonsoNeural',
 'Spanish (United States)-Paloma-Female': 'es-US-PalomaNeural',
 'Spanish (Uruguay)-Mateo-Male': 'es-UY-MateoNeural',
 'Spanish (Uruguay)-Valentina-Female': 'es-UY-ValentinaNeural',
 'Spanish (Venezuela)-Paola-Female': 'es-VE-PaolaNeural',
 'Spanish (Venezuela)-Sebastian-Male': 'es-VE-SebastianNeural',
 'Estonian (Estonia)-Anu-Female': 'et-EE-AnuNeural',
 'Estonian (Estonia)-Kert-Male': 'et-EE-KertNeural',
 'Persian (Iran)-Dilara-Female': 'fa-IR-DilaraNeural',
 'Persian (Iran)-Farid-Male': 'fa-IR-FaridNeural',
 'Finnish (Finland)-Harri-Male': 'fi-FI-HarriNeural',
 'Finnish (Finland)-Noora-Female': 'fi-FI-NooraNeural',
 'French (Belgium)-Charline-Female': 'fr-BE-CharlineNeural',
 'French (Belgium)-Gerard-Male': 'fr-BE-GerardNeural',
 'French (Canada)-Sylvie-Female': 'fr-CA-SylvieNeural',
 'French (Canada)-Antoine-Male': 'fr-CA-AntoineNeural',
 'French (Canada)-Jean-Male': 'fr-CA-JeanNeural',
 'French (Switzerland)-Ariane-Female': 'fr-CH-ArianeNeural',
 'French (Switzerland)-Fabrice-Male': 'fr-CH-FabriceNeural',
 'French (France)-Denise-Female': 'fr-FR-DeniseNeural',
 'French (France)-Eloise-Female': 'fr-FR-EloiseNeural',
 'French (France)-Henri-Male': 'fr-FR-HenriNeural',
 'Chinese (Mandarin, Simplified)-Xiaoxiao-Female': 'zh-CN-XiaoxiaoNeural',
 'Chinese (Mandarin, Simplified)-Yunyang-Male': 'zh-CN-YunyangNeural',
 'Chinese (Mandarin, Simplified)-Yunxi-Male': 'zh-CN-YunxiNeural',
 'Chinese (Mandarin, Simplified)-Xiaoyi-Female': 'zh-CN-XiaoyiNeural',
 'Chinese (Mandarin, Simplified)-Yunjian-Male': 'zh-CN-YunjianNeural',
 'Chinese (Mandarin, Simplified)-Yunxia-Male': 'zh-CN-YunxiaNeural',
 'Chinese (Northeastern Mandarin, Simplified)-Xiaobei-Female': 'zh-CN-liaoning-XiaobeiNeural',
 'Chinese (Zhongyuan Mandarin Shaanxi, Simplified)-Xiaoni-Female': 'zh-CN-shaanxi-XiaoniNeural',
 'Chinese (Cantonese, Traditional)-HiuMaan-Female': 'zh-HK-HiuMaanNeural',
 'Chinese (Cantonese, Traditional)-HiuGaai-Female': 'zh-HK-HiuGaaiNeural',
 'Chinese (Cantonese, Traditional)-WanLung-Male': 'zh-HK-WanLungNeural',
 'Chinese (Taiwanese Mandarin)-HsiaoChen-Female': 'zh-TW-HsiaoChenNeural',
 'Chinese (Taiwanese Mandarin)-HsiaoYu-Female': 'zh-TW-HsiaoYuNeural',
 'Chinese (Taiwanese Mandarin)-YunJhe-Male': 'zh-TW-YunJheNeural',
  'German (Austria)-Ingrid-Female': 'de-AT-IngridNeural',
 'German (Austria)-Jonas-Male': 'de-AT-JonasNeural',
 'German (Switzerland)-Jan-Male': 'de-CH-JanNeural',
 'German (Switzerland)-Leni-Female': 'de-CH-LeniNeural',
 'German (Germany)-Katja-Female': 'de-DE-KatjaNeural',
 'German (Germany)-Amala-Female': 'de-DE-AmalaNeural',
 'German (Germany)-Conrad-Male': 'de-DE-ConradNeural',
 'German (Germany)-Killian-Male': 'de-DE-KillianNeural',
 'Hindi (India)-Madhur-Male': 'hi-IN-MadhurNeural',
 'Hindi (India)-Swara-Female': 'hi-IN-SwaraNeural',
  'Italian (Italy)-Isabella-Female': 'it-IT-IsabellaNeural',
 'Italian (Italy)-Diego-Male': 'it-IT-DiegoNeural',
 'Italian (Italy)-Elsa-Female': 'it-IT-ElsaNeural',
 'Japanese (Japan)-Nanami-Female': 'ja-JP-NanamiNeural',
 'Japanese (Japan)-Keita-Male': 'ja-JP-KeitaNeural',
 'Korean (Korea)-Sun-Hi-Female': 'ko-KR-SunHiNeural',
 'Korean (Korea)-InJoon-Male': 'ko-KR-InJoonNeural',
 'Portuguese (Brazil)-Francisca-Female': 'pt-BR-FranciscaNeural',
 'Portuguese (Brazil)-Antonio-Male': 'pt-BR-AntonioNeural',
 'Portuguese (Portugal)-Duarte-Male': 'pt-PT-DuarteNeural',
 'Portuguese (Portugal)-Raquel-Female': 'pt-PT-RaquelNeural',
 'Afrikaans (South Africa)-Adri-Female': 'af-ZA-AdriNeural',
 'Afrikaans (South Africa)-Willem-Male': 'af-ZA-WillemNeural',
 'Amharic (Ethiopia)-Ameha-Male': 'am-ET-AmehaNeural',
 'Amharic (Ethiopia)-Mekdes-Female': 'am-ET-MekdesNeural',
 'Arabic (United Arab Emirates)-Fatima-Female': 'ar-AE-FatimaNeural',
 'Arabic (United Arab Emirates)-Hamdan-Male': 'ar-AE-HamdanNeural',
 'Arabic (Bahrain)-Ali-Male': 'ar-BH-AliNeural',
 'Arabic (Bahrain)-Laila-Female': 'ar-BH-LailaNeural',
 'Arabic (Algeria)-Ismael-Male': 'ar-DZ-IsmaelNeural',
 'Arabic (Egypt)-Salma-Female': 'ar-EG-SalmaNeural',
 'Arabic (Egypt)-Shakir-Male': 'ar-EG-ShakirNeural',
 'Arabic (Iraq)-Bassel-Male': 'ar-IQ-BasselNeural',
 'Arabic (Iraq)-Rana-Female': 'ar-IQ-RanaNeural',
 'Arabic (Jordan)-Sana-Female': 'ar-JO-SanaNeural',
 'Arabic (Jordan)-Taim-Male': 'ar-JO-TaimNeural',
 'Arabic (Kuwait)-Fahed-Male': 'ar-KW-FahedNeural',
 'Arabic (Kuwait)-Noura-Female': 'ar-KW-NouraNeural',
 'Arabic (Lebanon)-Layla-Female': 'ar-LB-LaylaNeural',
 'Arabic (Lebanon)-Rami-Male': 'ar-LB-RamiNeural',
 'Arabic (Libya)-Iman-Female': 'ar-LY-ImanNeural',
 'Arabic (Libya)-Omar-Male': 'ar-LY-OmarNeural',
 'Arabic (Morocco)-Jamal-Male': 'ar-MA-JamalNeural',
 'Arabic (Morocco)-Mouna-Female': 'ar-MA-MounaNeural',
 'Arabic (Oman)\u200b-Abdullah-Male': 'ar-OM-AbdullahNeural',
 'Arabic (Oman)\u200b-Aysha-Female': 'ar-OM-AyshaNeural',
 'Arabic (Qatar)-Amal-Female': 'ar-QA-AmalNeural',
 'Arabic (Qatar)-Moaz-Male': 'ar-QA-MoazNeural',
 'Arabic (Saudi Arabia)-Hamed-Male': 'ar-SA-HamedNeural',
 'Arabic (Saudi Arabia)-Zariyah-Female': 'ar-SA-ZariyahNeural',
 'Arabic (Syria)-Amany-Female': 'ar-SY-AmanyNeural',
 'Arabic (Syria)-Laith-Male': 'ar-SY-LaithNeural',
 'Arabic (Tunisia)-Hedi-Male': 'ar-TN-HediNeural',
 'Arabic (Tunisia)-Reem-Female': 'ar-TN-ReemNeural',
 'Arabic (Yemen)-Maryam-Female': 'ar-YE-MaryamNeural',
 'Arabic (Yemen)-Saleh-Male': 'ar-YE-SalehNeural',
 'Azerbaijani (Azerbaijan)-Babek-Male': 'az-AZ-BabekNeural',
 'Azerbaijani (Azerbaijan)-Banu-Female': 'az-AZ-BanuNeural',
 'Bulgarian (Bulgaria)-Borislav-Male': 'bg-BG-BorislavNeural',
 'Bulgarian (Bulgaria)-Kalina-Female': 'bg-BG-KalinaNeural',
 'Bangla (Bangladesh)-Nabanita-Female': 'bn-BD-NabanitaNeural',
 'Bangla (Bangladesh)-Pradeep-Male': 'bn-BD-PradeepNeural',
 'Bengali (India)-Bashkar-Male': 'bn-IN-BashkarNeural',
 'Bengali (India)-Tanishaa-Female': 'bn-IN-TanishaaNeural',
 'Bosnian (Bosnia)-Goran-Male': 'bs-BA-GoranNeural',
 'Bosnian (Bosnia)-Vesna-Female': 'bs-BA-VesnaNeural',
 'Catalan (Spain)-Joana-Female': 'ca-ES-JoanaNeural',
 'Catalan (Spain)-Enric-Male': 'ca-ES-EnricNeural',
 'Czech (Czech)-Antonin-Male': 'cs-CZ-AntoninNeural',
 'Czech (Czech)-Vlasta-Female': 'cs-CZ-VlastaNeural',
 'Welsh (United Kingdom)-Aled-Male': 'cy-GB-AledNeural',
 'Welsh (United Kingdom)-Nia-Female': 'cy-GB-NiaNeural',
 'Danish (Denmark)-Christel-Female': 'da-DK-ChristelNeural',
 'Danish (Denmark)-Jeppe-Male': 'da-DK-JeppeNeural',
 'Greek (Greece)-Athina-Female': 'el-GR-AthinaNeural',
 'Greek (Greece)-Nestoras-Male': 'el-GR-NestorasNeural',
 'Irish (Ireland)-Colm-Male': 'ga-IE-ColmNeural',
 'Irish (Ireland)-Orla-Female': 'ga-IE-OrlaNeural',
 'Galician (Spain)-Roi-Male': 'gl-ES-RoiNeural',
 'Galician (Spain)-Sabela-Female': 'gl-ES-SabelaNeural',
 'Gujarati (India)-Dhwani-Female': 'gu-IN-DhwaniNeural',
 'Gujarati (India)-Niranjan-Male': 'gu-IN-NiranjanNeural',
 'Hebrew (Israel)-Avri-Male': 'he-IL-AvriNeural',
 'Hebrew (Israel)-Hila-Female': 'he-IL-HilaNeural',
 'Croatian (Croatia)-Gabrijela-Female': 'hr-HR-GabrijelaNeural',
 'Croatian (Croatia)-Srecko-Male': 'hr-HR-SreckoNeural',
 'Hungarian (Hungary)-Noemi-Female': 'hu-HU-NoemiNeural',
 'Hungarian (Hungary)-Tamas-Male': 'hu-HU-TamasNeural',
 'Indonesian (Indonesia)-Ardi-Male': 'id-ID-ArdiNeural',
 'Indonesian (Indonesia)-Gadis-Female': 'id-ID-GadisNeural',
 'Icelandic (Iceland)-Gudrun-Female': 'is-IS-GudrunNeural',
 'Icelandic (Iceland)-Gunnar-Male': 'is-IS-GunnarNeural',
 'Javanese (Indonesia)-Dimas-Male': 'jv-ID-DimasNeural',
 'Javanese (Indonesia)-Siti-Female': 'jv-ID-SitiNeural',
 'Georgian (Georgia)-Eka-Female': 'ka-GE-EkaNeural',
 'Georgian (Georgia)-Giorgi-Male': 'ka-GE-GiorgiNeural',
 'Kazakh (Kazakhstan)-Aigul-Female': 'kk-KZ-AigulNeural',
 'Kazakh (Kazakhstan)-Daulet-Male': 'kk-KZ-DauletNeural',
 'Khmer (Cambodia)-Piseth-Male': 'km-KH-PisethNeural',
 'Khmer (Cambodia)-Sreymom-Female': 'km-KH-SreymomNeural',
 'Kannada (India)-Gagan-Male': 'kn-IN-GaganNeural',
 'Kannada (India)-Sapna-Female': 'kn-IN-SapnaNeural',
 'Lao (Laos)-Chanthavong-Male': 'lo-LA-ChanthavongNeural',
 'Lao (Laos)-Keomany-Female': 'lo-LA-KeomanyNeural',
 'Lithuanian (Lithuania)-Leonas-Male': 'lt-LT-LeonasNeural',
 'Lithuanian (Lithuania)-Ona-Female': 'lt-LT-OnaNeural',
 'Latvian (Latvia)-Everita-Female': 'lv-LV-EveritaNeural',
 'Latvian (Latvia)-Nils-Male': 'lv-LV-NilsNeural',
 'Macedonian (Republic of North Macedonia)-Aleksandar-Male': 'mk-MK-AleksandarNeural',
 'Macedonian (Republic of North Macedonia)-Marija-Female': 'mk-MK-MarijaNeural',
 'Malayalam (India)-Midhun-Male': 'ml-IN-MidhunNeural',
 'Malayalam (India)-Sobhana-Female': 'ml-IN-SobhanaNeural',
 'Mongolian (Mongolia)-Bataa-Male': 'mn-MN-BataaNeural',
 'Mongolian (Mongolia)-Yesui-Female': 'mn-MN-YesuiNeural',
 'Marathi (India)-Aarohi-Female': 'mr-IN-AarohiNeural',
 'Marathi (India)-Manohar-Male': 'mr-IN-ManoharNeural',
 'Malay (Malaysia)-Osman-Male': 'ms-MY-OsmanNeural',
 'Malay (Malaysia)-Yasmin-Female': 'ms-MY-YasminNeural',
 'Maltese (Malta)-Grace-Female': 'mt-MT-GraceNeural',
 'Maltese (Malta)-Joseph-Male': 'mt-MT-JosephNeural',
 'Burmese (Myanmar)-Nilar-Female': 'my-MM-NilarNeural',
 'Burmese (Myanmar)-Thiha-Male': 'my-MM-ThihaNeural',
 'Norwegian (Bokmål, Norway)-Pernille-Female': 'nb-NO-PernilleNeural',
 'Norwegian (Bokmål, Norway)-Finn-Male': 'nb-NO-FinnNeural',
 'Nepali (Nepal)-Hemkala-Female': 'ne-NP-HemkalaNeural',
 'Nepali (Nepal)-Sagar-Male': 'ne-NP-SagarNeural',
 'Dutch (Belgium)-Arnaud-Male': 'nl-BE-ArnaudNeural',
 'Dutch (Belgium)-Dena-Female': 'nl-BE-DenaNeural',
 'Dutch (Netherlands)-Colette-Female': 'nl-NL-ColetteNeural',
 'Dutch (Netherlands)-Fenna-Female': 'nl-NL-FennaNeural',
 'Dutch (Netherlands)-Maarten-Male': 'nl-NL-MaartenNeural',
 'Polish (Poland)-Marek-Male': 'pl-PL-MarekNeural',
 'Polish (Poland)-Zofia-Female': 'pl-PL-ZofiaNeural',
 'Pashto (Afghanistan)-Gul Nawaz-Male': 'ps-AF-GulNawazNeural',
 'Pashto (Afghanistan)-Latifa-Female': 'ps-AF-LatifaNeural',
 'Romanian (Romania)-Alina-Female': 'ro-RO-AlinaNeural',
 'Romanian (Romania)-Emil-Male': 'ro-RO-EmilNeural',
 'Russian (Russia)-Svetlana-Female': 'ru-RU-SvetlanaNeural',
 'Russian (Russia)-Dmitry-Male': 'ru-RU-DmitryNeural',
 'Sinhala (Sri Lanka)-Sameera-Male': 'si-LK-SameeraNeural',
 'Sinhala (Sri Lanka)-Thilini-Female': 'si-LK-ThiliniNeural',
 'Slovak (Slovakia)-Lukas-Male': 'sk-SK-LukasNeural',
 'Slovak (Slovakia)-Viktoria-Female': 'sk-SK-ViktoriaNeural',
 'Slovenian (Slovenia)-Petra-Female': 'sl-SI-PetraNeural',
 'Slovenian (Slovenia)-Rok-Male': 'sl-SI-RokNeural',
 'Somali (Somalia)-Muuse-Male': 'so-SO-MuuseNeural',
 'Somali (Somalia)-Ubax-Female': 'so-SO-UbaxNeural',
 'Albanian (Albania)-Anila-Female': 'sq-AL-AnilaNeural',
 'Albanian (Albania)-Ilir-Male': 'sq-AL-IlirNeural',
 'Serbian (Serbia)-Nicholas-Male': 'sr-RS-NicholasNeural',
 'Serbian (Serbia)-Sophie-Female': 'sr-RS-SophieNeural',
 'Sundanese (Indonesia)-Jajang-Male': 'su-ID-JajangNeural',
 'Sundanese (Indonesia)-Tuti-Female': 'su-ID-TutiNeural',
 'Swedish (Sweden)-Sofie-Female': 'sv-SE-SofieNeural',
 'Swedish (Sweden)-Mattias-Male': 'sv-SE-MattiasNeural',
 'Swahili (Kenya)-Rafiki-Male': 'sw-KE-RafikiNeural',
 'Swahili (Kenya)-Zuri-Female': 'sw-KE-ZuriNeural',
 'Swahili (Tanzania)-Daudi-Male': 'sw-TZ-DaudiNeural',
 'Swahili (Tanzania)-Rehema-Female': 'sw-TZ-RehemaNeural',
 'Tamil (India)-Pallavi-Female': 'ta-IN-PallaviNeural',
 'Tamil (India)-Valluvar-Male': 'ta-IN-ValluvarNeural',
 'Tamil (Sri Lanka)-Kumar-Male': 'ta-LK-KumarNeural',
 'Tamil (Sri Lanka)-Saranya-Female': 'ta-LK-SaranyaNeural',
 'Tamil (Malaysia)-Kani-Female': 'ta-MY-KaniNeural',
 'Tamil (Malaysia)-Surya-Male': 'ta-MY-SuryaNeural',
 'Tamil (Singapore)-Anbu-Male': 'ta-SG-AnbuNeural',
 'Telugu (India)-Mohan-Male': 'te-IN-MohanNeural',
 'Telugu (India)-Shruti-Female': 'te-IN-ShrutiNeural',
 'Thai (Thailand)-Premwadee-Female': 'th-TH-PremwadeeNeural',
 'Thai (Thailand)-Niwat-Male': 'th-TH-NiwatNeural',
 'Turkish (Turkey)-Ahmet-Male': 'tr-TR-AhmetNeural',
 'Turkish (Turkey)-Emel-Female': 'tr-TR-EmelNeural',
 'Ukrainian (Ukraine)-Ostap-Male': 'uk-UA-OstapNeural',
 'Ukrainian (Ukraine)-Polina-Female': 'uk-UA-PolinaNeural',
 'Urdu (India)-Gul-Female': 'ur-IN-GulNeural',
 'Urdu (India)-Salman-Male': 'ur-IN-SalmanNeural',
 'Urdu (Pakistan)-Asad-Male': 'ur-PK-AsadNeural',
 'Urdu (Pakistan)-Uzma-Female': 'ur-PK-UzmaNeural',
 'Uzbek (Uzbekistan)-Madina-Female': 'uz-UZ-MadinaNeural',
 'Uzbek (Uzbekistan)-Sardor-Male': 'uz-UZ-SardorNeural',
 'Vietnamese (Vietnam)-HoaiMy-Female': 'vi-VN-HoaiMyNeural',
 'Vietnamese (Vietnam)-NamMinh-Male': 'vi-VN-NamMinhNeural',
 'Zulu (South Africa)-Thando-Female': 'zu-ZA-ThandoNeural',
 'Zulu (South Africa)-Themba-Male': 'zu-ZA-ThembaNeural'}
